// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v5.29.2
// source: sendmail.proto

package pb

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	SendmailService_SendmailVerification_FullMethodName = "/pb.SendmailService/SendmailVerification"
)

// SendmailServiceClient is the client API for SendmailService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type SendmailServiceClient interface {
	SendmailVerification(ctx context.Context, in *SendmailVerificationRequest, opts ...grpc.CallOption) (*SendmailVerificationResponse, error)
}

type sendmailServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewSendmailServiceClient(cc grpc.ClientConnInterface) SendmailServiceClient {
	return &sendmailServiceClient{cc}
}

func (c *sendmailServiceClient) SendmailVerification(ctx context.Context, in *SendmailVerificationRequest, opts ...grpc.CallOption) (*SendmailVerificationResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(SendmailVerificationResponse)
	err := c.cc.Invoke(ctx, SendmailService_SendmailVerification_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// SendmailServiceServer is the server API for SendmailService service.
// All implementations must embed UnimplementedSendmailServiceServer
// for forward compatibility.
type SendmailServiceServer interface {
	SendmailVerification(context.Context, *SendmailVerificationRequest) (*SendmailVerificationResponse, error)
	mustEmbedUnimplementedSendmailServiceServer()
}

// UnimplementedSendmailServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedSendmailServiceServer struct{}

func (UnimplementedSendmailServiceServer) SendmailVerification(context.Context, *SendmailVerificationRequest) (*SendmailVerificationResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method SendmailVerification not implemented")
}
func (UnimplementedSendmailServiceServer) mustEmbedUnimplementedSendmailServiceServer() {}
func (UnimplementedSendmailServiceServer) testEmbeddedByValue()                         {}

// UnsafeSendmailServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to SendmailServiceServer will
// result in compilation errors.
type UnsafeSendmailServiceServer interface {
	mustEmbedUnimplementedSendmailServiceServer()
}

func RegisterSendmailServiceServer(s grpc.ServiceRegistrar, srv SendmailServiceServer) {
	// If the following call pancis, it indicates UnimplementedSendmailServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&SendmailService_ServiceDesc, srv)
}

func _SendmailService_SendmailVerification_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SendmailVerificationRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SendmailServiceServer).SendmailVerification(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: SendmailService_SendmailVerification_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SendmailServiceServer).SendmailVerification(ctx, req.(*SendmailVerificationRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// SendmailService_ServiceDesc is the grpc.ServiceDesc for SendmailService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var SendmailService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "pb.SendmailService",
	HandlerType: (*SendmailServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "SendmailVerification",
			Handler:    _SendmailService_SendmailVerification_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "sendmail.proto",
}
