// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.5
// 	protoc        v5.29.2
// source: sendmail.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type SendmailVerificationRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Email         string                 `protobuf:"bytes,1,opt,name=email,proto3" json:"email,omitempty"`
	Otp           string                 `protobuf:"bytes,2,opt,name=otp,proto3" json:"otp,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SendmailVerificationRequest) Reset() {
	*x = SendmailVerificationRequest{}
	mi := &file_sendmail_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SendmailVerificationRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SendmailVerificationRequest) ProtoMessage() {}

func (x *SendmailVerificationRequest) ProtoReflect() protoreflect.Message {
	mi := &file_sendmail_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SendmailVerificationRequest.ProtoReflect.Descriptor instead.
func (*SendmailVerificationRequest) Descriptor() ([]byte, []int) {
	return file_sendmail_proto_rawDescGZIP(), []int{0}
}

func (x *SendmailVerificationRequest) GetEmail() string {
	if x != nil {
		return x.Email
	}
	return ""
}

func (x *SendmailVerificationRequest) GetOtp() string {
	if x != nil {
		return x.Otp
	}
	return ""
}

type SendmailVerificationResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SendmailVerificationResponse) Reset() {
	*x = SendmailVerificationResponse{}
	mi := &file_sendmail_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SendmailVerificationResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SendmailVerificationResponse) ProtoMessage() {}

func (x *SendmailVerificationResponse) ProtoReflect() protoreflect.Message {
	mi := &file_sendmail_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SendmailVerificationResponse.ProtoReflect.Descriptor instead.
func (*SendmailVerificationResponse) Descriptor() ([]byte, []int) {
	return file_sendmail_proto_rawDescGZIP(), []int{1}
}

var File_sendmail_proto protoreflect.FileDescriptor

var file_sendmail_proto_rawDesc = string([]byte{
	0x0a, 0x0e, 0x73, 0x65, 0x6e, 0x64, 0x6d, 0x61, 0x69, 0x6c, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f,
	0x12, 0x02, 0x70, 0x62, 0x22, 0x45, 0x0a, 0x1b, 0x53, 0x65, 0x6e, 0x64, 0x6d, 0x61, 0x69, 0x6c,
	0x56, 0x65, 0x72, 0x69, 0x66, 0x69, 0x63, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x52, 0x65, 0x71, 0x75,
	0x65, 0x73, 0x74, 0x12, 0x14, 0x0a, 0x05, 0x65, 0x6d, 0x61, 0x69, 0x6c, 0x18, 0x01, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x05, 0x65, 0x6d, 0x61, 0x69, 0x6c, 0x12, 0x10, 0x0a, 0x03, 0x6f, 0x74, 0x70,
	0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x03, 0x6f, 0x74, 0x70, 0x22, 0x1e, 0x0a, 0x1c, 0x53,
	0x65, 0x6e, 0x64, 0x6d, 0x61, 0x69, 0x6c, 0x56, 0x65, 0x72, 0x69, 0x66, 0x69, 0x63, 0x61, 0x74,
	0x69, 0x6f, 0x6e, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x32, 0x6e, 0x0a, 0x0f, 0x53,
	0x65, 0x6e, 0x64, 0x6d, 0x61, 0x69, 0x6c, 0x53, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x12, 0x5b,
	0x0a, 0x14, 0x53, 0x65, 0x6e, 0x64, 0x6d, 0x61, 0x69, 0x6c, 0x56, 0x65, 0x72, 0x69, 0x66, 0x69,
	0x63, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x12, 0x1f, 0x2e, 0x70, 0x62, 0x2e, 0x53, 0x65, 0x6e, 0x64,
	0x6d, 0x61, 0x69, 0x6c, 0x56, 0x65, 0x72, 0x69, 0x66, 0x69, 0x63, 0x61, 0x74, 0x69, 0x6f, 0x6e,
	0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x20, 0x2e, 0x70, 0x62, 0x2e, 0x53, 0x65, 0x6e,
	0x64, 0x6d, 0x61, 0x69, 0x6c, 0x56, 0x65, 0x72, 0x69, 0x66, 0x69, 0x63, 0x61, 0x74, 0x69, 0x6f,
	0x6e, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x00, 0x42, 0x05, 0x5a, 0x03, 0x2f,
	0x70, 0x62, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
})

var (
	file_sendmail_proto_rawDescOnce sync.Once
	file_sendmail_proto_rawDescData []byte
)

func file_sendmail_proto_rawDescGZIP() []byte {
	file_sendmail_proto_rawDescOnce.Do(func() {
		file_sendmail_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_sendmail_proto_rawDesc), len(file_sendmail_proto_rawDesc)))
	})
	return file_sendmail_proto_rawDescData
}

var file_sendmail_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_sendmail_proto_goTypes = []any{
	(*SendmailVerificationRequest)(nil),  // 0: pb.SendmailVerificationRequest
	(*SendmailVerificationResponse)(nil), // 1: pb.SendmailVerificationResponse
}
var file_sendmail_proto_depIdxs = []int32{
	0, // 0: pb.SendmailService.SendmailVerification:input_type -> pb.SendmailVerificationRequest
	1, // 1: pb.SendmailService.SendmailVerification:output_type -> pb.SendmailVerificationResponse
	1, // [1:2] is the sub-list for method output_type
	0, // [0:1] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_sendmail_proto_init() }
func file_sendmail_proto_init() {
	if File_sendmail_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_sendmail_proto_rawDesc), len(file_sendmail_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_sendmail_proto_goTypes,
		DependencyIndexes: file_sendmail_proto_depIdxs,
		MessageInfos:      file_sendmail_proto_msgTypes,
	}.Build()
	File_sendmail_proto = out.File
	file_sendmail_proto_goTypes = nil
	file_sendmail_proto_depIdxs = nil
}
