services:
  zookeeper:
    image: quay.io/debezium/zookeeper:2.7
    container_name: demo_zookeeper
    ports:
      - "2181:2181"
      - "2888:2888"
      - "3888:3888"
  kafka0:
      image: quay.io/debezium/kafka:2.7
      restart: always
      ports:
        - '9092:9092'
        - '29092:29092'
      links:
        - zookeeper
      environment:
        - ZOOKEEPER_CONNECT=zookeeper:2181
        - KAFKA_LISTENERS=INTERNAL://0.0.0.0:9092,EXTERNAL://0.0.0.0:29092
        - KAFKA_ADVERTISED_LISTENERS=INTERNAL://kafka0:9092,EXTERNAL://localhost:29092
        - KAFKA_LISTENER_SECURITY_PROTOCOL_MAP=INTERNAL:PLAINTEXT,EXTERNAL:PLAINTEXT
        - KAFKA_INTER_BROKER_LISTENER_NAME=INTERNAL
  kafka-ui:
      image: provectuslabs/kafka-ui:latest
      container_name: demo_kafka-ui
      environment:
        KAFKA_CLUSTERS_0_NAME: local
        KAFKA_CLUSTERS_0_BOOTSTRAPSERVERS: kafka0:9092
      ports:
        - "9089:8080"
      links:
        - kafka0