// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v5.29.2
// source: proto/discord-logs-bot.proto

package discord_logs

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	DiscordLogsService_SendLogsMessage_FullMethodName = "/pb.DiscordLogsService/SendLogsMessage"
)

// DiscordLogsServiceClient is the client API for DiscordLogsService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type DiscordLogsServiceClient interface {
	SendLogsMessage(ctx context.Context, in *SendLogsMessageRequest, opts ...grpc.CallOption) (*SendLogsMessageResponse, error)
}

type discordLogsServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewDiscordLogsServiceClient(cc grpc.ClientConnInterface) DiscordLogsServiceClient {
	return &discordLogsServiceClient{cc}
}

func (c *discordLogsServiceClient) SendLogsMessage(ctx context.Context, in *SendLogsMessageRequest, opts ...grpc.CallOption) (*SendLogsMessageResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(SendLogsMessageResponse)
	err := c.cc.Invoke(ctx, DiscordLogsService_SendLogsMessage_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// DiscordLogsServiceServer is the server API for DiscordLogsService service.
// All implementations must embed UnimplementedDiscordLogsServiceServer
// for forward compatibility.
type DiscordLogsServiceServer interface {
	SendLogsMessage(context.Context, *SendLogsMessageRequest) (*SendLogsMessageResponse, error)
	mustEmbedUnimplementedDiscordLogsServiceServer()
}

// UnimplementedDiscordLogsServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedDiscordLogsServiceServer struct{}

func (UnimplementedDiscordLogsServiceServer) SendLogsMessage(context.Context, *SendLogsMessageRequest) (*SendLogsMessageResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method SendLogsMessage not implemented")
}
func (UnimplementedDiscordLogsServiceServer) mustEmbedUnimplementedDiscordLogsServiceServer() {}
func (UnimplementedDiscordLogsServiceServer) testEmbeddedByValue()                            {}

// UnsafeDiscordLogsServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to DiscordLogsServiceServer will
// result in compilation errors.
type UnsafeDiscordLogsServiceServer interface {
	mustEmbedUnimplementedDiscordLogsServiceServer()
}

func RegisterDiscordLogsServiceServer(s grpc.ServiceRegistrar, srv DiscordLogsServiceServer) {
	// If the following call pancis, it indicates UnimplementedDiscordLogsServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&DiscordLogsService_ServiceDesc, srv)
}

func _DiscordLogsService_SendLogsMessage_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SendLogsMessageRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DiscordLogsServiceServer).SendLogsMessage(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: DiscordLogsService_SendLogsMessage_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DiscordLogsServiceServer).SendLogsMessage(ctx, req.(*SendLogsMessageRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// DiscordLogsService_ServiceDesc is the grpc.ServiceDesc for DiscordLogsService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var DiscordLogsService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "pb.DiscordLogsService",
	HandlerType: (*DiscordLogsServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "SendLogsMessage",
			Handler:    _DiscordLogsService_SendLogsMessage_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "proto/discord-logs-bot.proto",
}
