// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.28.0

package database

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type TblAccount struct {
	UserID         pgtype.UUID
	UserAccount    string
	UserPassword   string
	UserSalt       string
	UserLoginTime  pgtype.Timestamp
	UserLogoutTime pgtype.Timestamp
	UserLoginIp    pgtype.Text
	UserRole       int32
	UserCreatedAt  pgtype.Timestamp
	UserUpdatedAt  pgtype.Timestamp
}

type TblToken struct {
	ID           pgtype.UUID
	UserID       pgtype.UUID
	PublicKey    string
	RefreshToken string
}
